# import the table from phase 1
counts_phase1 <- read.table("/Users/BarbaraMaria/Dropbox/projects/2016_dsx-phase2/data/OnthophagusCounts.tsv",header=T)

# enter new header names to include small/large
colnames(counts_phase1)<-c("gene",
"large_ctrl_male_brain_s19",
"large_ctrl_male_brain_s20",
"large_ctrl_male_brain_s21",
"large_ctrl_male_brain_s22",
"large_ctrl_male_brain_s23",
"large_ctrl_male_brain_s24",
"large_ctrl_male_th_s43",
"large_ctrl_male_th_s44",
"large_ctrl_male_th_s45",
"large_ctrl_male_th_s46",
"large_ctrl_male_th_s47",
"large_ctrl_male_th_s48",
"large_ctrl_male_hh_s67",
"large_ctrl_male_hh_s68",
"large_ctrl_male_hh_s69",
"large_ctrl_male_hh_s70",
"large_ctrl_male_hh_s71",
"large_ctrl_male_hh_s72",
"large_ctrl_male_gen_s91",
"large_ctrl_male_gen_s92",
"large_ctrl_male_gen_s93",
"large_ctrl_male_gen_s94",
"large_ctrl_male_gen_s95",
"large_ctrl_male_gen_s96",
"large_ctrl_female_brain_s13",
"large_ctrl_female_brain_s14",
"large_ctrl_female_brain_s15",
"large_ctrl_female_brain_s16",
"large_ctrl_female_brain_s17",
"large_ctrl_female_brain_s18",
"large_ctrl_female_th_s37",
"large_ctrl_female_th_s38",
"large_ctrl_female_th_s39",
"large_ctrl_female_th_s40",
"large_ctrl_female_th_s41",
"large_ctrl_female_th_s42",
"large_ctrl_female_hh_s61",
"large_ctrl_female_hh_s62",
"large_ctrl_female_hh_s63",
"large_ctrl_female_hh_s64",
"large_ctrl_female_hh_s65",
"large_ctrl_female_hh_s66",
"large_ctrl_female_gen_s85",
"large_ctrl_female_gen_s86",
"large_ctrl_female_gen_s87",
"large_ctrl_female_gen_s88",
"large_ctrl_female_gen_s89",
"large_ctrl_female_gen_s90",
"large_dsx_male_brain_s7",
"large_dsx_male_brain_s8",
"large_dsx_male_brain_s9",
"large_dsx_male_brain_s10",
"large_dsx_male_brain_s11",
"large_dsx_male_brain_s12",
"large_dsx_male_th_s31",
"large_dsx_male_th_s32",
"large_dsx_male_th_s33",
"large_dsx_male_th_s34",
"large_dsx_male_th_s35",
"large_dsx_male_th_s36",
"large_dsx_male_hh_s55",
"large_dsx_male_hh_s56",
"large_dsx_male_hh_s57",
"large_dsx_male_hh_s58",
"large_dsx_male_hh_s59",
"large_dsx_male_hh_s60",
"large_dsx_male_gen_s79",
"large_dsx_male_gen_s80",
"large_dsx_male_gen_s81",
"large_dsx_male_gen_s82",
"large_dsx_male_gen_s83",
"large_dsx_male_gen_s84",
"large_dsx_female_brain_s1",
"large_dsx_female_brain_s2",
"large_dsx_female_brain_s3",
"large_dsx_female_brain_s4",
"large_dsx_female_brain_s5",
"large_dsx_female_brain_s6",
"large_dsx_female_th_s25",
"large_dsx_female_th_s26",
"large_dsx_female_th_s27",
"large_dsx_female_th_s28",
"large_dsx_female_th_s29",
"large_dsx_female_th_s30",
"large_dsx_female_hh_s49",
"large_dsx_female_hh_s50",
"large_dsx_female_hh_s51",
"large_dsx_female_hh_s52",
"large_dsx_female_hh_s53",
"large_dsx_female_hh_s54",
"large_dsx_female_gen_s73",
"large_dsx_female_gen_s74",
"large_dsx_female_gen_s75",
"large_dsx_female_gen_s76",
"large_dsx_female_gen_s77",
"large_dsx_female_gen_s78")

# save it as a separate file:
write.table(as.data.frame(counts_phase1), file="/Users/BarbaraMaria/Dropbox/projects/2016_dsx-phase2/data/counts_phase1.tsv",sep="\t",row.names=FALSE,col.names=TRUE,quote=FALSE)

# import the table from phase 2a
counts_phase2a <- read.table("/Users/BarbaraMaria/Dropbox/projects/2016_dsx-phase2/data/counts.tsv")

# but the phase2 source table does not have column names; so add them:
# these are the column names for the second dataset
colnames(counts_phase2a)<-c("gene",
"small_dsx_male_brain_s97",
"small_dsx_male_brain_s98",
"small_dsx_male_brain_s99",
"small_dsx_male_brain_s100",
"small_dsx_male_brain_s101",
"small_dsx_male_brain_s102",

"small_ctrl_male_brain_s103",
"small_ctrl_male_brain_s104",
"small_ctrl_male_brain_s105",
"small_ctrl_male_brain_s106",
"small_ctrl_male_brain_s107",
"small_ctrl_male_brain_s108",

"small_dsx_male_th_s109",
"small_dsx_male_th_s110",
"small_dsx_male_th_s111",
"small_dsx_male_th_s112",
"small_dsx_male_th_s113",
"small_dsx_male_th_s114",

"small_ctrl_male_th_s115",
"small_ctrl_male_th_s116",
"small_ctrl_male_th_s117",
"small_ctrl_male_th_s118",
"small_ctrl_male_th_s119",
"small_ctrl_male_th_s120",

"small_dsx_male_hh_s121",
"small_dsx_male_hh_s122",
"small_dsx_male_hh_s123",
"small_dsx_male_hh_s124",
"small_dsx_male_hh_s125",
"small_dsx_male_hh_s126",

"small_ctrl_male_hh_s127",
"small_ctrl_male_hh_s128",
"small_ctrl_male_hh_s129",
"small_ctrl_male_hh_s130",
"small_ctrl_male_hh_s131",
"small_ctrl_male_hh_s132",

"small_dsx_male_gen_s133",
"small_dsx_male_gen_s134",
"small_dsx_male_gen_s135",
"small_dsx_male_gen_s136",
"small_dsx_male_gen_s137",
"small_dsx_male_gen_s138",

"small_ctrl_male_gen_s139",
"small_ctrl_male_gen_s140",
"small_ctrl_male_gen_s141",
"small_ctrl_male_gen_s142",
"small_ctrl_male_gen_s143",
"small_ctrl_male_gen_s144")

#save phase 2 as a separate file
write.table(as.data.frame(counts_phase2a), file="/Users/BarbaraMaria/Dropbox/projects/2016_dsx-phase2/data/counts_phase2a.tsv",sep="\t",row.names=FALSE,col.names=TRUE,quote=FALSE)

#merge both databases
counts_all <- merge(counts_phase1,counts_phase2a,by="gene")

#save both databases
write.table(as.data.frame(counts_all), file="/Users/BarbaraMaria/Dropbox/projects/2016_dsx-phase2/data/counts_all.tsv",sep="\t",row.names=FALSE,col.names=TRUE,quote=FALSE)